FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
 && pip install setuptools \
 && pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY data ./data

EXPOSE 7860

CMD ["python", "src/gradio_app.py"]