# Dockerfile.worker
FROM python:3.12-slim

RUN useradd --create-home --shell /bin/bash appuser
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev curl git \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./src /app/src
COPY ./data /app/data

USER appuser

CMD ["celery", "-A", "src.celery_app.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
