
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip \
 && pip install --default-timeout=1000 --retries 10 --no-cache-dir -r requirements.txt

COPY src ./src
COPY data ./data

CMD ["celery","-A","src.celery_app","worker","--loglevel=info"]