[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:pythonjsonlogger.*
    ignore::PendingDeprecationWarning:starlette.*
    ignore::DeprecationWarning:sqlalchemy.*
asyncio_mode = auto
