name: Provider Validator CI

# Trigger on pushes to main/master/dev, PRs against those branches,
# and tag pushes (tags trigger the docker build+push step).
on:
  push:
    branches: [ main, master, dev ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, master, dev ]

jobs:
  tests:
    name: Run Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-asyncio

      - name: Run lint (optional)
        run: |
          source venv/bin/activate
          if [ -f setup.cfg ] || [ -f .flake8 ]; then
            echo "Running flake8"
            pip install flake8
            flake8 || true
          fi

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v --disable-warnings

  build-and-push:
    name: Build & Push Docker (on tag)
    needs: tests
    runs-on: ubuntu-latest
    # run this job only when a tag matching v*.*.* is pushed
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            prasanna/provider-validator:${{ github.ref_name }}
            prasanna/provider-validator:latest
